ALTER TABLE public.monthly_reports
  ADD COLUMN IF NOT EXISTS outstanding_loans_ars NUMERIC NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS outstanding_loans_usd NUMERIC NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS members_overdue INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS members_late_payment INTEGER NOT NULL DEFAULT 0;